
apiVersion: kyverno.io/v2
kind: ClusterCleanupPolicy
metadata:
  name: cleanup-completed-pods
spec:
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - "*"   # Explicitly match all namespaces
  # Only delete pods whose phase is Succeeded or Failed (kubectl shows this as "Completed" and "Error")
  conditions:
    any:
      - key: "{{ target.status.phase }}"
        operator: Equals
        value: "Succeeded"
      - key: "{{ target.status.phase }}"
        operator: Equals
        value: "Failed"
  # Cron schedule (minute hour day-of-month month day-of-week)
  schedule: "*/5 * * * *"
